const BLUE_THEME_COLOR = '#008AC3'
const ERROR_THEME_COLOR = '#ff2900'
const BUTTON_BACKGROUND_COLOR = '#f9f5ed'
const SUCCESS_THEME_COLOR = '#006600'

export {
  BLUE_THEME_COLOR,
  ERROR_THEME_COLOR,
  BUTTON_BACKGROUND_COLOR,
  SUCCESS_THEME_COLOR,
}